#!/bin/bash

set -eu

PUBKEY_PATH=$HOME/.ssh/id_ed25519.pub

[ ! -e $PUBKEY_PATH ] && ssh-keygen -t ed25519

GITHUB_PUBKEY=`cat $PUBKEY_PATH`

read -s -p 'GitHub Personal Access Token: ' GITHUB_PAT
echo

curl -XPOST \
  -H "Content-Type: application/json" \
  -H "Authorization: token $GITHUB_PAT" \
  -d "{\"title\": \"$USER@$HOSTNAME\", \"key\": \"$GITHUB_PUBKEY\"}" \
  "https://api.github.com/user/keys"
